version: '3.5'

services:
  diarating:
    image: diarating
    build: .
    container_name: diarating
    restart: always
    networks:
      - postgres
    env_file:
      - ./.env

networks:
  postgres:  
    external: true